[project]
name = "flostra-backend"
version = "0.1.0"
description = "Flostra Backend"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.122.0",
    "longchain>=0.4.2",
    "openai>=2.8.1",
    "uvicorn>=0.38.0",
]
